# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43d6b9b5b4bd0261f641787cebcbd594c90e7cc36cc61431dfa79ea9bc2da9fcbe100729f75d4e24c24b24f9eb714dc28b87089549525669f5fa5cc998f68dc9

test:
  secret_key_base: ff7f8f43d093e795576fb037854836153291bd3c5b58c144945095409d244879c881a13afd789c327f5cc34aeaa8aff6d23b3ce4a0e148dcc5079b9e9ba9da20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
